CREATE TABLE APPOINTMENTS(
APP_ID INT NOT NULL PRIMARY KEY,
DOC_ID INT NULL,
PAT_ID INT NULL,
APP_DATE DATETIME NULL,
STATUS ENUM("SCHEDULED","COMPLETED","CANCELLED"),

CONSTRAINT FOREIGN KEY(DOC_ID) REFERENCES DOCTORS(DOC_ID),

CONSTRAINT FOREIGN KEY(PAT_ID) REFERENCES PATIENTS(PAT_ID)
);