CREATE TABLE BILLS(
BILL_ID INT NOT NULL PRIMARY KEY,
APP_ID INT NULL,
AMOUNT DECIMAL(10,2) NULL,
PAYMENT_STATUS ENUM("PAID","UNPAID") NULL,

CONSTRAINT FOREIGN KEY(APP_ID) REFERENCES APPOINTMENTS(APP_ID)

);