CREATE TABLE MEDICATION(

MED_ID INT NOT NULL PRIMARY KEY,
PAT_ID INT NULL,
DOC_ID INT NULL,
MEDICINE_NAME VARCHAR(100) NULL,
DOSAGE VARCHAR(50) NULL,
START_DATE DATE NULL,
END_DATE DATE NULL,

CONSTRAINT FOREIGN KEY(PAT_ID) REFERENCES PATIENTS(PAT_ID),

CONSTRAINT FOREIGN KEY(DOC_ID) REFERENCES DOCTORS(DOC_ID)

);