-- Use Existing Database
USE CHOMBU;

-- =========================
-- BRANCH TABLE
-- =========================
CREATE TABLE BRANCH(
    BID INT UNSIGNED NOT NULL,
    BNAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL,
    PINCODE INT UNSIGNED NOT NULL,

    CONSTRAINT P_BID PRIMARY KEY(BID),
    CONSTRAINT U_PIN UNIQUE(PINCODE),
    CONSTRAINT C_PIN CHECK(LENGTH(PINCODE) = 6)
);