CREATE TABLE PRODUCT(
PID INT NOT NULL,
PNAME VARCHAR(10) NOT NULL,
PRICE DECIMAL(5,2) NOT NULL,
QUANTITY INT NULL,

CONSTRAINT P_PID PRIMARY KEY(PID),
CONSTRAINT C_PRICE CHECK(PRICE>0),
CONSTRAINT C_QUANTITY CHECK(QUANTITY>0)

);