-- Create Database
CREATE DATABASE IF NOT EXISTS CHOMBU;

-- Use Database
USE CHOMBU;

-- =========================
-- STUDENT TABLE
-- =========================
CREATE TABLE STUDENT(
    SID INT UNSIGNED NOT NULL,
    SNAME VARCHAR(20) NOT NULL,
    PHONE BIGINT UNSIGNED NOT NULL,

    CONSTRAINT P_SID PRIMARY KEY(SID),
    CONSTRAINT U_PH UNIQUE(PHONE),
    CONSTRAINT C_PH CHECK(LENGTH(PHONE) = 10)
);