CREATE TABLE BOOKINGS(
BOOKING_ID INT NOT NULL PRIMARY KEY,
CUSTOMER_ID INT NULL,
PACKAGE_ID INT NULL,
BOOKING_DATE DATE NULL,
STATUS ENUM("CONFIRMED","CANCELLED","PENDING") NULL,
CONSTRAINT FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT FOREIGN KEY(PACKAGE_ID) REFERENCES PACKAGES(PACKAGE_ID)
);