CREATE TABLE PACKAGES(
PACKAGE_ID INT NOT NULL PRIMARY KEY,
DESTINATION_ID INT NULL,
PACKAGE_NAME VARCHAR(100) NULL,
DURATION_DAYS INT NULL,
PRICE DECIMAL(10,2) NULL,
CONSTRAINT FOREIGN KEY(DESTINATION_ID) REFERENCES DESTINATION(DESTINATION_ID)
);